name: CI

on:
  push:
    branches: [ "r" ]
  pull_request:
    branches: [ "r" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenSSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Configure SSH Server
        run: |
          sudo mkdir -p /var/run/sshd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Set root password
        run: echo "root:root" | sudo chpasswd

      - name: Verify SSH Server
        run: |
          sudo systemctl status ssh || true
          sudo netstat -tuln | grep :22 || true

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Download ngrok
        run: curl -sO https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz

      - name: Extract ngrok
        run: tar -xvzf ngrok-v3-stable-linux-amd64.tgz

      - name: Set ngrok auth token
        run: ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start ngrok tunnel
        id: ngrok
        run: ./ngrok tcp 22
