name: CI

on:
  push:
    branches: [ "r" ]
  pull_request:
    branches: [ "r" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install OpenSSH Server
        run: sudo apt-get update && sudo apt-get install -y openssh-server
        shell: bash

      - name: Configure SSH Server
        run: |
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh start
        shell: bash

      - name: Set root password
        run: echo "root:rootpassword" | sudo chpasswd
        shell: bash

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash

      - name: Download ngrok
        run: curl -sO https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        shell: bash

      - name: Extract ngrok
        run: tar -xvzf ngrok-v3-stable-linux-amd64.tgz
        shell: bash

      - name: Set ngrok auth token
        run: ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}
        shell: bash

      - name: Start ngrok tunnel
        id: ngrok
        run: ./ngrok tcp 22
        shell: bash
