name: ssh-tunnel

on:
  push:
    branches: [ "r" ]
  pull_request:
    branches: [ "r" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSSH Server
        run: sudo apt-get update && sudo apt-get install -y openssh-server
        
      - name: Set Password for SSH User
        run: |
          echo "root:root" | sudo chpasswd
          echo "runner:root" | sudo chpasswd

      - name: Configure SSH Server
        run: |
          sudo mkdir -p /var/run/sshd
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication no" | sudo tee -a /etc/ssh/sshd_config
          sudo service ssh start

      - name: Add SSH Public Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          sudo service ssh restart

      - name: Read Subdomain from File
        id: read_subdomain
        run: |
          SUBDOMAIN=$(cat subdomain.txt) # Ganti dengan path ke file Anda
          echo "subdomain=${SUBDOMAIN}" >> $GITHUB_ENV

      - name: Start SSH Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -R "${{ env.subdomain }}:22:localhost:22" serveo.net
